spring:
  datasource:
    url: ${TEST_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${TEST_DB_PASSWORD}
  thymeleaf:
    cache: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      properties:
        hibernate.id.new_generator_mappings: false
      ddl-auto: none
    show-sql: false