spring:
  datasource:
    url: ${TEST_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${TEST_DB_PASSWORD}
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      properties:
          hibernate.id.new_generator_mappings: false
      ddl-auto: validate
    show-sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google